export const PLAYERONE_STATS = 'PLAYERONE_STATS';
export const PLAYERONE_MOUNTS = 'PLAYERONE_MOUNTS';
export const PLAYERONE_PETS = 'PLAYERONE_PETS';
export const PLAYERONE_GEAR = 'PLAYERONE_GEAR';
export const PLAYERONE_PROG = 'PLAYERONE_PROG';
export const PLAYERONE_TALENTS = 'PLAYERONE_TALENTS';
export const PLAYERONE_REGION = 'PLAYERONE_REGION';
export const PLAYERONE_MYTHICS = 'PLAYERONE_MYTHICS';
export const PLAYERONE_NO_MYTHICS = 'PLAYERONE_NO_MYTHICS';
export const PLAYERONE_MYTHIC_SCORE = 'PLAYERONE_MYTHIC_SCORE';
export const PLAYERONE_ERROR = 'PLAYERONE_ERROR';

export const PLAYERTWO_STATS = 'PLAYERTWO_STATS';
export const PLAYERTWO_MOUNTS = 'PLAYERTWO_MOUNTS';
export const PLAYERTWO_PETS = 'PLAYERTWO_PETS';
export const PLAYERTWO_GEAR = 'PLAYERTWO_GEAR';
export const PLAYERTWO_PROG = 'PLAYERTWO_PROG';
export const PLAYERTWO_TALENTS = 'PLAYERTWO_TALENTS';
export const PLAYERTWO_REGION = 'PLAYERTWO_REGION';
export const PLAYERTWO_MYTHICS = 'PLAYERTWO_MYTHICS';
export const PLAYERTWO_MYTHIC_SCORE = 'PLAYERTWO_MYTHIC_SCORE';
export const PLAYERTWO_NO_MYTHICS = 'PLAYERTWO_NO_MYTHICS';
export const PLAYERTWO_ERROR = 'PLAYERTWO_ERROR';

// Admin Mutation Types
export const ADMIN_LOGIN = 'ADMIN_LOGIN';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';

// User
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGOUT = 'USER_LOGOUT';
